### ISSUE TITLE
Add/Enable Travis-CI

### ISSUE THREAD

**Issue by pwelch** [rondale-sc/remote_pair_chef#25]
Add and Enable [Travis-CI](https://travis-ci.org/) to run tests for any pull requests.

**Comment by rondale-sc** [comment]
I'm down with this.  Want to pair up on it for a bit?

**Comment by pwelch** [comment]
Resolved on [Pull Request #26 ](https://github.com/rondale-sc/remote_pair_chef/pull/26)
